receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317
#  prometheus:
#    config:
#      scrape_configs:
#        - job_name: otel-collector-metrics
#          scrape_interval: 10s
#          static_configs:
#            - targets: [ '127.0.0.1:8888' ]
#        - job_name: grafana-metrics
#          scrape_interval: 10s
#          static_configs:
#            - targets: [ 'grafana:3000' ]
processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 1500
    spike_limit_mib: 512
extensions:
  health_check: {}
exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlphttp/prometheus:
    endpoint: "http://prometheus:9090/api/v1/write"
#    encoding: proto
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    enable_open_metrics: true
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  otlphttp/logs:
    endpoint: "http://loki:3100/otlp"
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
#      processors: [memory_limiter, batch]
      exporters: [otlp/tempo, otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
#      processors: [memory_limiter, batch]
      exporters: [prometheus]
    logs:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ otlphttp/logs ]